# Generated by Django 5.2.8 on 2026-08-21 10:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("assinatura_ativa", models.BooleanField(default=True)),
                ("assinatura_valida_ate", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Plano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60)),
                ("slug", models.SlugField(unique=True)),
                (
                    "preco_mensal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "limite_veiculos",
                    models.PositiveIntegerField(default=0, help_text="0 = ilimitado"),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["preco_mensal"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("gestor", "Gestor"),
                            ("operador", "Operador"),
                            ("consulta", "Consulta"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfis",
                        to="contas.organizacao",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organizacao",
            name="plano",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizacoes",
                to="contas.plano",
            ),
        ),
    ]
