# Generated by Django 5.2.8 on 2026-08-24 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="organizacao",
            field=models.ForeignKey(
                blank=True,
                help_text="Vazio para o administrador global do sistema.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfis",
                to="contas.organizacao",
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="papel",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador do sistema"),
                    ("gestor", "Gestor da organização"),
                    ("operador", "Operador (motorista)"),
                ],
                default="gestor",
                max_length=20,
            ),
        ),
    ]
