# Generated by Django 5.2.8 on 2026-08-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0003_migrar_papeis"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logotipo exibido no topo do sistema (opcional).",
                null=True,
                upload_to="logos/",
            ),
        ),
    ]
