# Generated by Django 5.2.8 on 2026-08-24 19:24

from django.db import migrations, models


def limpar_logos_antigos(apps, schema_editor):
    """Os valores antigos eram caminhos de arquivo (ImageField), invalidos como
    data URI. Zera para evitar imagem quebrada; a logo sera reenviada."""
    Organizacao = apps.get_model("contas", "Organizacao")
    for org in Organizacao.objects.exclude(logo="").exclude(logo__startswith="data:"):
        org.logo = ""
        org.save(update_fields=["logo"])


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0004_organizacao_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizacao",
            name="logo",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Logotipo (miniatura) exibido no topo do sistema.",
            ),
        ),
        migrations.RunPython(limpar_logos_antigos, migrations.RunPython.noop),
    ]
