# Generated by Django 5.2.8 on 2026-09-25 17:54

import uuid
from django.db import migrations, models


def gerar_tokens(apps, schema_editor):
    """Gera um token unico por organizacao existente (o default do AddField
    aplicaria o mesmo valor a todas as linhas)."""
    Organizacao = apps.get_model("contas", "Organizacao")
    for org in Organizacao.objects.all():
        org.token_convite = uuid.uuid4()
        org.save(update_fields=["token_convite"])


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0005_alter_organizacao_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="token_convite",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gerar_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="organizacao",
            name="token_convite",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="papel",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador do sistema"),
                    ("gestor", "Gestor da organização"),
                    ("operador", "Operador (motorista)"),
                    ("solicitante", "Solicitante (pré-agendamento)"),
                ],
                default="gestor",
                max_length=20,
            ),
        ),
    ]
