# Generated by Django 5.2.8 on 2025-11-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
