# Generated by Django 5.2.8 on 2025-11-19 12:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0002_veiculo_picture_veiculo_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='show',
            new_name='Show',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Manutenção')], default='ativo', max_length=20),
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('combustivel', 'Combustível'), ('manutencao', 'Manutenção'), ('seguro', 'Seguro'), ('ipva', 'IPVA'), ('lavagem', 'Lavagem'), ('estacionamento', 'Estacionamento'), ('multa', 'Multa'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='carro.veiculo')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
