# Generated by Django 5.2.8 on 2026-08-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0004_rename_data_compra_remove_show_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("combustivel", "⛽ Combustível"),
                    ("manutencao", "⚙️ Manutenção"),
                    ("seguro", "🛡️ Seguro"),
                    ("ipva", "💰 IPVA"),
                    ("lavagem", "💧 Lavagem"),
                    ("estacionamento", "🅿️ Estacionamento"),
                    ("multa", "🚨 Multa"),
                    ("outro", "📌 Outro"),
                ],
                max_length=20,
            ),
        ),
    ]
