# Generated by Django 5.2.8 on 2026-08-20 03:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0005_alter_custo_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abastecimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("quilometragem", models.PositiveIntegerField()),
                ("litros", models.DecimalField(decimal_places=3, max_digits=8)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tipo_combustivel",
                    models.CharField(
                        choices=[
                            ("gasolina", "Gasolina"),
                            ("etanol", "Etanol"),
                            ("diesel", "Diesel"),
                            ("gnv", "GNV"),
                            ("flex", "Flex"),
                        ],
                        default="gasolina",
                        max_length=20,
                    ),
                ),
                ("posto", models.CharField(blank=True, max_length=100)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abastecimentos",
                        to="carro.veiculo",
                    ),
                ),
            ],
            options={
                "ordering": ["-data", "-quilometragem"],
            },
        ),
        migrations.CreateModel(
            name="PlanoManutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=120)),
                (
                    "intervalo_km",
                    models.PositiveIntegerField(
                        blank=True, help_text="A cada quantos km (opcional)", null=True
                    ),
                ),
                (
                    "intervalo_dias",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="A cada quantos dias (opcional)",
                        null=True,
                    ),
                ),
                (
                    "km_referencia",
                    models.PositiveIntegerField(
                        blank=True, help_text="Km da ultima realizacao", null=True
                    ),
                ),
                (
                    "data_referencia",
                    models.DateField(
                        blank=True, help_text="Data da ultima realizacao", null=True
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planos_manutencao",
                        to="carro.veiculo",
                    ),
                ),
            ],
            options={
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="RegistroQuilometragem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("quilometragem", models.PositiveIntegerField()),
                ("origem", models.CharField(blank=True, max_length=100)),
                ("observacao", models.TextField(blank=True)),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_km",
                        to="carro.veiculo",
                    ),
                ),
            ],
            options={
                "ordering": ["-data", "-quilometragem"],
            },
        ),
    ]
