# Generated by Django 5.2.8 on 2026-08-21 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0006_abastecimento_planomanutencao_registroquilometragem"),
    ]

    operations = [
        migrations.AddField(
            model_name="abastecimento",
            name="custo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="abastecimento",
                to="carro.custo",
            ),
        ),
        migrations.AddField(
            model_name="custo",
            name="comprovante",
            field=models.FileField(
                blank=True,
                help_text="Foto/PDF da nota ou comprovante (opcional).",
                null=True,
                upload_to="comprovantes/",
            ),
        ),
        migrations.AddField(
            model_name="custo",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dinheiro", "Dinheiro"),
                    ("pix", "Pix"),
                    ("debito", "Cartão de débito"),
                    ("credito", "Cartão de crédito"),
                    ("boleto", "Boleto"),
                    ("outro", "Outro"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="custo",
            name="fornecedor",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="custo",
            name="quilometragem",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Km do veiculo no momento do custo (opcional).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="meta_custo_mensal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Orcamento de custo por mes (opcional). Usado nos alertas.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
