# Generated by Django 5.2.8 on 2026-08-21 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0007_abastecimento_custo_custo_comprovante_and_more"),
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="organizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="veiculos",
                to="contas.organizacao",
            ),
        ),
        migrations.AddIndex(
            model_name="custo",
            index=models.Index(
                fields=["veiculo", "data"], name="carro_custo_veiculo_1b5948_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="custo",
            index=models.Index(fields=["data"], name="carro_custo_data_f4bc97_idx"),
        ),
        migrations.AddIndex(
            model_name="veiculo",
            index=models.Index(
                fields=["organizacao", "status"], name="carro_veicu_organiz_ac41d6_idx"
            ),
        ),
    ]
