# Generated by Django 5.2.8 on 2026-08-21 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0009_povoar_organizacao"),
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="organizacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="veiculos",
                to="contas.organizacao",
            ),
        ),
    ]
