# Generated by Django 5.2.8 on 2026-08-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0010_veiculo_organizacao_obrigatoria"),
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="chassi",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="combustivel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gasolina", "Gasolina"),
                    ("etanol", "Etanol"),
                    ("diesel", "Diesel"),
                    ("gnv", "GNV"),
                    ("flex", "Flex"),
                    ("eletrico", "Elétrico"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="observacoes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="placa",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="renavam",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="valor_aquisicao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor pago na aquisicao (opcional).",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="veiculo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("placa", ""), _negated=True),
                fields=("organizacao", "placa"),
                name="placa_unica_por_org",
            ),
        ),
    ]
