# Generated by Django 5.2.8 on 2026-08-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0011_veiculo_chassi_veiculo_combustivel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("licenciamento", "Licenciamento"),
                            ("seguro", "Seguro"),
                            ("ipva", "IPVA"),
                            ("crlv", "CRLV"),
                            ("multa", "Multa"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vencimento", models.DateField()),
                ("observacao", models.CharField(blank=True, max_length=200)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="carro.veiculo",
                    ),
                ),
            ],
            options={
                "ordering": ["vencimento"],
                "indexes": [
                    models.Index(
                        fields=["veiculo", "vencimento"],
                        name="carro_docum_veiculo_91ae46_idx",
                    )
                ],
            },
        ),
    ]
