# Generated by Django 5.2.8 on 2026-08-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0012_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="custo",
            name="grupo",
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AddField(
            model_name="custo",
            name="parcela_numero",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="custo",
            name="parcela_total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
