# Generated by Django 5.2.8 on 2026-08-23 21:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0013_custo_grupo_custo_parcela_numero_custo_parcela_total"),
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motorista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("cpf", models.CharField(blank=True, max_length=14)),
                (
                    "cnh",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número da CNH"
                    ),
                ),
                (
                    "cnh_categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("AB", "AB"),
                            ("AC", "AC"),
                            ("AD", "AD"),
                            ("AE", "AE"),
                        ],
                        max_length=2,
                    ),
                ),
                ("cnh_validade", models.DateField(blank=True, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=10,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "data_cadastro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motoristas",
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="AtribuicaoVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField(default=django.utils.timezone.now)),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("observacao", models.CharField(blank=True, max_length=200)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atribuicoes",
                        to="carro.veiculo",
                    ),
                ),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atribuicoes",
                        to="carro.motorista",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_inicio", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="motorista",
            index=models.Index(
                fields=["organizacao", "status"], name="carro_motor_organiz_7c0f0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atribuicaoveiculo",
            index=models.Index(
                fields=["veiculo", "data_inicio"], name="carro_atrib_veiculo_bd93eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atribuicaoveiculo",
            index=models.Index(
                fields=["motorista", "data_inicio"],
                name="carro_atrib_motoris_faccc0_idx",
            ),
        ),
    ]
