# Generated by Django 5.2.8 on 2026-09-21 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0015_motorista_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="custo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documento",
                to="carro.custo",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="valor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Taxa paga pelo documento (opcional). Vira um custo do veiculo.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="custo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("combustivel", "⛽ Combustível"),
                    ("manutencao", "⚙️ Manutenção"),
                    ("licenciamento", "📄 Licenciamento"),
                    ("seguro", "🛡️ Seguro"),
                    ("ipva", "💰 IPVA"),
                    ("lavagem", "💧 Lavagem"),
                    ("estacionamento", "🅿️ Estacionamento"),
                    ("multa", "🚨 Multa"),
                    ("outro", "📌 Outro"),
                ],
                max_length=20,
            ),
        ),
    ]
