# Generated by Django 5.2.8 on 2026-09-25 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0016_documento_custo_documento_valor_alter_custo_tipo"),
        ("contas", "0006_organizacao_token_convite_alter_perfilusuario_papel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("setor", models.CharField(blank=True, max_length=120)),
                ("cpf", models.CharField(blank=True, max_length=14)),
                (
                    "cnh",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número da CNH"
                    ),
                ),
                (
                    "cnh_categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("AB", "AB"),
                            ("AC", "AC"),
                            ("AD", "AD"),
                            ("AE", "AE"),
                        ],
                        max_length=2,
                    ),
                ),
                ("cnh_validade", models.DateField(blank=True, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Aguardando aprovação"),
                            ("ativo", "Ativo"),
                            ("inativo", "Inativo"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitantes",
                        to="contas.organizacao",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitante",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setor", models.CharField(max_length=120)),
                ("saida_prevista", models.DateTimeField()),
                ("retorno_previsto", models.DateTimeField()),
                ("destino", models.CharField(max_length=200)),
                (
                    "precisa_motorista",
                    models.BooleanField(
                        default=False,
                        help_text="O solicitante precisa de um motorista designado?",
                    ),
                ),
                ("justificativa", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Aguardando aprovação"),
                            ("aprovada", "Aprovada"),
                            ("recusada", "Recusada"),
                            ("em_uso", "Em uso"),
                            ("devolvida", "Devolvida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=12,
                    ),
                ),
                ("data_decisao", models.DateTimeField(blank=True, null=True)),
                ("motivo_recusa", models.CharField(blank=True, max_length=200)),
                ("retorno_real", models.DateTimeField(blank=True, null=True)),
                ("km_final", models.PositiveIntegerField(blank=True, null=True)),
                ("obs_devolucao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes_decididas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "atribuicao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes",
                        to="carro.atribuicaoveiculo",
                    ),
                ),
                (
                    "motorista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes",
                        to="carro.motorista",
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes_veiculo",
                        to="contas.organizacao",
                    ),
                ),
                (
                    "registro_km",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes",
                        to="carro.registroquilometragem",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes",
                        to="carro.veiculo",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes",
                        to="carro.solicitante",
                    ),
                ),
            ],
            options={
                "ordering": ["-saida_prevista", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="solicitante",
            index=models.Index(
                fields=["organizacao", "status"], name="carro_solic_organiz_d823a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solicitacaoveiculo",
            index=models.Index(
                fields=["organizacao", "status"], name="carro_solic_organiz_db9953_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solicitacaoveiculo",
            index=models.Index(
                fields=["veiculo", "saida_prevista"],
                name="carro_solic_veiculo_a539c9_idx",
            ),
        ),
    ]
