# Generated by Django 5.2.8 on 2026-09-25 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0017_solicitante_solicitacaoveiculo_and_more"),
        ("contas", "0006_organizacao_token_convite_alter_perfilusuario_papel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalaDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("observacao", models.CharField(blank=True, max_length=200)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalas",
                        to="carro.motorista",
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalas",
                        to="contas.organizacao",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalas",
                        to="carro.veiculo",
                    ),
                ),
            ],
            options={
                "ordering": ["-data", "veiculo__marca", "veiculo__modelo"],
                "indexes": [
                    models.Index(
                        fields=["organizacao", "data"],
                        name="carro_escal_organiz_284278_idx",
                    ),
                    models.Index(
                        fields=["motorista", "data"],
                        name="carro_escal_motoris_7771fd_idx",
                    ),
                    models.Index(
                        fields=["veiculo", "data"],
                        name="carro_escal_veiculo_35fab6_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("veiculo", "data"), name="escala_unica_por_veiculo_dia"
                    ),
                    models.UniqueConstraint(
                        fields=("motorista", "data"),
                        name="escala_unica_por_motorista_dia",
                    ),
                ],
            },
        ),
    ]
