# Generated by Django 5.2.8 on 2026-09-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0019_migrar_vinculos_para_escala"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoveiculo",
            name="km_inicial",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitacaoveiculo",
            name="saida_real",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitante",
            name="cargo",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
