# Generated by Django 5.2.8 on 2026-09-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0020_solicitacaoveiculo_km_inicial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escaladiaria",
            name="destino",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
