# Generated by Django 5.2.8 on 2026-10-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carro", "0021_escaladiaria_destino"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="foto",
            field=models.TextField(blank=True, default=""),
        ),
    ]
